name: Auto Generate LinkedIn Post

on:
  schedule:
    - cron: '0 9 * * *'  # Run every day at 9 AM UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytrends feedparser google-generativeai requests python-dotenv

    - name: Run script
      run: python main.py

    - name: Upload result (Optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: post-output
        path: post.txt
